# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_pb2 as service__pb2


class WaterControllerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetConfig = channel.unary_unary(
                '/WaterController/SetConfig',
                request_serializer=service__pb2.Configuration.SerializeToString,
                response_deserializer=service__pb2.Status.FromString,
                )
        self.GetValues = channel.unary_unary(
                '/WaterController/GetValues',
                request_serializer=service__pb2.Configuration.SerializeToString,
                response_deserializer=service__pb2.Values.FromString,
                )


class WaterControllerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def SetConfig(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValues(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WaterControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=service__pb2.Configuration.FromString,
                    response_serializer=service__pb2.Status.SerializeToString,
            ),
            'GetValues': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValues,
                    request_deserializer=service__pb2.Configuration.FromString,
                    response_serializer=service__pb2.Values.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WaterController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WaterController(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WaterController/SetConfig',
            service__pb2.Configuration.SerializeToString,
            service__pb2.Status.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WaterController/GetValues',
            service__pb2.Configuration.SerializeToString,
            service__pb2.Values.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
