version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ../../../../persist/postgres-data:/var/lib/postgresql/data
  web:
    image: wateringcontrol:latest
    environment:
      - DJANGO_SECRET=${DJANGO_SECRET}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ENVIRONMENT=${ENVIRONMENT}
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
