version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DOCKER}
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DOCKER}
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
