version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:z
  web:
    build: .
    environment:
      - DJANGO_SECRET=test
      - POSTGRES_PASSWORD=test
      - ENVIRONMENT=local
    volumes:
      - ./:/host/code:z
    expose:
      - "8001"
      - "8000"
      - "80"
      - "443"
    ports:
      - "8001:8001"
      - "8000:8000"
      - "80:80"
      - "443:443"
    depends_on:
      - db
