# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: web/grpc/service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16web/grpc/service.proto\x1a\x1cgoogle/protobuf/struct.proto\"4\n\x05Input\x12+\n\nproperties\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"5\n\x06Output\x12+\n\nproperties\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"9\n\nController\x12+\n\nproperties\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"`\n\rConfiguration\x12\x15\n\x05input\x18\x01 \x01(\x0b\x32\x06.Input\x12\x17\n\x06output\x18\x02 \x01(\x0b\x32\x07.Output\x12\x1f\n\ncontroller\x18\x03 \x01(\x0b\x32\x0b.Controller\"8\n\x0e\x43onfigurations\x12&\n\x0e\x63onfigurations\x18\x01 \x03(\x0b\x32\x0e.Configuration\"\x14\n\x06Status\x12\n\n\x02ok\x18\x02 \x01(\x08\"&\n\x05Value\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\" \n\x06Values\x12\x16\n\x06values\x18\x05 \x03(\x0b\x32\x06.Value2g\n\x0fWaterController\x12,\n\x0e\x41\x64\x64\x43ontrollers\x12\x0f.Configurations\x1a\x07.Status\"\x00\x12&\n\tGetValues\x12\x0e.Configuration\x1a\x07.Values\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'web.grpc.service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPUT._serialized_start=56
  _INPUT._serialized_end=108
  _OUTPUT._serialized_start=110
  _OUTPUT._serialized_end=163
  _CONTROLLER._serialized_start=165
  _CONTROLLER._serialized_end=222
  _CONFIGURATION._serialized_start=224
  _CONFIGURATION._serialized_end=320
  _CONFIGURATIONS._serialized_start=322
  _CONFIGURATIONS._serialized_end=378
  _STATUS._serialized_start=380
  _STATUS._serialized_end=400
  _VALUE._serialized_start=402
  _VALUE._serialized_end=440
  _VALUES._serialized_start=442
  _VALUES._serialized_end=474
  _WATERCONTROLLER._serialized_start=476
  _WATERCONTROLLER._serialized_end=579
# @@protoc_insertion_point(module_scope)
