# Generated by Django 2.1.2 on 2018-11-19 21:08

from django.db import migrations, models


def migration(apps, schema_editor):
    Device = apps.get_model('web', 'Device')
    OutputDevice = apps.get_model('web', 'OutputDevice')
    InputDevice = apps.get_model('web', 'InputDevice')
    for device in Device.objects.all():
        if device.device_type == 'input':
            new_device = InputDevice(id=device.id,
                                     rp_channel=device.rp_channel,
                                     name=device.name,
                                     description=device.description,
                                     location=device.location,
            )
        else:
            new_device = OutputDevice(id=device.id,
                                     rp_channel=device.rp_channel,
                                     name=device.name,
                                     description=device.description,
                                     location=device.location,
            )
        new_device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_channel', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutputDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_channel', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(
            migration,
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
