# Generated by Django 2.2.2 on 2019-06-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181119_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnOffController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('is_active', models.BooleanField()),
                ('set_point', models.FloatField()),
                ('hysteresis', models.FloatField()),
                ('input_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.InputDevice')),
                ('output_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.OutputDevice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
