# Generated by Django 3.0.5 on 2020-04-12 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_onoffcontroller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='inputdevice',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Host'),
        ),
        migrations.AddField(
            model_name='onoffcontroller',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Host'),
        ),
        migrations.AddField(
            model_name='outputdevice',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Host'),
        ),
    ]
