# Generated by Django 3.2.10 on 2021-12-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_host_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onoffcontroller',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controllers', to='web.host'),
        ),
    ]
