apiVersion: apps/v1
kind: Deployment
metadata:
  name: watering-control-deployment
  labels:
    app: watering-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watering-control
  template:
    metadata:
      labels:
        app: watering-control
    spec:
      initContainers:
      - name: init-myservice
        image: ghcr.io/pettermk/watering-control:0.1.15
        envFrom:
        - secretRef:
            name: postgres-settings
        command: ['sh', '-c', "python manage.py migrate"]
      containers:
      - name: watering-control
        image: ghcr.io/pettermk/watering-control:0.1.15
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: PROD
        - name: OIDC_RSA_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: oidc-rsa-key
              key: oidc.key
        envFrom:
        - secretRef:
            name: postgres-settings
        - secretRef:
            name: django-secrets
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: watering-control-service
spec:
  selector:
    app: watering-control
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  type: ClusterIP