apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: watering-control-db
spec:
  instances: 2
  bootstrap:
    initdb:
      database: watering-control
      owner: watering-control
      postInitApplicationSQL:
        - 'GRANT ALL ON SCHEMA public TO "watering-control";'
  storage:
    size: 3Gi

  backup:
    barmanObjectStore:
      destinationPath: "https://cloudnativepgbackups.blob.core.windows.net/barman"
      azureCredentials:
        connectionString:
          name: azure-creds
          key: AZURE_STORAGE_CONNECTION_STRING
      wal:
        compression: gzip
        maxParallel: 2
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
        immediateCheckpoint: false
    retentionPolicy: "30d"

---

apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: scheduled-backup
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: watering-control-db
