apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: watering-control-db
spec:
  instances: 2
  bootstrap:
    initdb:
      database: watering-control
      owner: watering-control
      postInitApplicationSQL:
        - 'GRANT ALL ON SCHEMA public TO "watering-control";'
  storage:
    size: 3Gi
