# action.yml
name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wateringcontrol:latest
    - name: Restart docker compose
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
        ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      run: docker-compose up web -d
